version: '3.8'

services:
  mysql:
    build: .
    container_name: metamoji
    environment:
      MYSQL_DATABASE: metamoji_db1
      MYSQL_USER: metamoji
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql